language: node_js
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: kGp0TEiEFs4kkX/MBOlkaD9jBBkVBZOpi6G6ZlzxdfTq4TO1dVbk7H8RLCbWQD3K78FCVb/3nDqd4BDai1Ce+kNPUoc/IYvpT0G/Ye8K7LYRHw/fqcEyhc2A2Lc0XGnPqfbMhM0kzvFRNV58BNWh2UjMw4AkxH3Hvqzb6tnndJN/c58CbuWWeY1AMQUGyvfB+NvhzudNcY7RMHvyUgIg4F6ETyMfm95zmxmhbNE5peNuGNSk02Aue4rWfWM+/APOpshzBW0VlItsuB5NTVzLklNLFPczbs9abUcrZeQlPpamzYyxzT1WxLeuEgwgUnCwInCZa2vmG16u+9+7WJSwAnHDiONAmytWBZ8p1fVieAY66+xQuIYcQrb4I9JMJOhw/YfJbDRLzQ9naqAEFhlsWyqUkbJoewJ7VkLlXP6n7CDEoN5QOOLEVCio2xExY80T4ihn116htubMhP2TPX76bT8qOQMLvVWSZZ29uQC9HdrN0j3IqpKIskvMtIlkZXneLNY/nh5VWIylV1V/u8+TLBEQeDR0L7IPAS9WTH8dhBVbQiAilEWOKS5X0mHF7RqIU8YyPsEgfNLVAnr/9q6kHX/gt+aILI6p64hRzbD3tzry1yDVZphZDMyu1f8bjGT5CBcUCXDudA0Z4GdJJ/uzwJQ0NxfUmhbHKa8fInPRXt0=
  on:
    tags: true
    repo: mahnunchik/vkminiapps-sign
